version: '3'
services:
  api:
    image: node:14.15.0
    working_dir: /code
    volumes:
      - type: bind
        source: ./server
        target: /code

  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=kakunatest
      - MONGO_INITDB_ROOT_PASSWORD=Test12
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
volumes:
  dbdata:
